### PR TITLE
Updates - scrum post

### PR DESCRIPTION
**Pull request by gandhiano**
Updating with scrum post, [US#108](https://tree.taiga.io/project/transformap/us/108)

### CODE REVIEW

**Comment by gandhiano** [comment]
Why is it sending me to @keikreutler repo, instead of Transformap one? Settings? Which one is actually rendering the page?

**Comment by gandhiano** [comment]
Well, reopening and trying to merge, at it seems this is the most recent repo. Please review later and provide some clarity on this @keikreutler @almereyda

**Comment by almereyda** [comment]
Merged with https://github.com/TransforMap/transformap.github.io/pull/12

**Comment by almereyda** [comment]
Merged into the git tree with https://github.com/TransforMap/transformap.github.io/pull/12

**Pull request closed without merging**
